### ISSUE TITLE
[REQ] 9x9-sudoku

### ISSUE THREAD

**Issue by norayr** [maemo-leste-extras/bugtracker#1]
Name: 9x9-sudoku
URL: https://github.com/norayr/9x9-sudoku
Comments: it works! I still have to cleanup unused dependencies and silence a couple of other warnings, but it compiles and works!

![](https://raw.githubusercontent.com/norayr/9x9-sudoku/master/screenshot/9x9-sudoku.png)

**Comment by MerlijnWajer** [comment]
Care to include a screenshot? :)

**Comment by norayr** [comment]
done (:

**Comment by parazyd** [comment]
Hi! Thanks for the contrib :)

I invited you as a maintainer to https://github.com/maemo-leste-extras/9x9-sudoku
Tomorrow I'll try to set up the rest so you can build it for our `extras` repository.

**Comment by norayr** [comment]
yay!

**Comment by parazyd** [comment]
Let me know when you accept the invite and are able to push the code :)

**Comment by parazyd** [comment]
Hi. I emailed you your credentials.

Also have a look at some maintenance instructions here: https://leste.maemo.org/Development/Building_Packages#Maintenance_workflow

**Comment by parazyd** [comment]
Done. Closing.
