### ISSUE TITLE
[REQ] Lirios cmake-shared

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste-extras/bugtracker#13]
https://github.com/IMbackK/cmake-shared

**Comment by parazyd** [comment]
Could you please split this into separate tickets? It's useful for tracking.

Thank you.

**Comment by IMbackK** [comment]
sure. btw these all have maemo/beowulf branches with debian packages.

**Comment by parazyd** [comment]
Invited here: https://github.com/maemo-leste-extras/lirios-cmake-shared
