### ISSUE TITLE
[REQ] pyfuelpad

### ISSUE THREAD

**Issue by javiplx** [maemo-leste-extras/bugtracker#2]
Name: pyfuelpad
URL: https://gitlab.com/javiplx/pyfuelpad, http://maemo.org/packages/view/pyfuelpad/
Comments: Packaging is updated, and I've verified that it actually runs both on the virtual machine and on pinephone. It should be usable although I'm still pending to compare code of published packages, current git and the one running on my device.

**Comment by parazyd** [comment]
Thank you!
I will set this up for you tomorrow :) Are you also in our IRC channel?

**Comment by MerlijnWajer** [comment]
Cool to see more python packages glad the pythons work. Just as a note -- the maemo.org page mentions GPS. We don't have liblocation yet, so I assume that doesn't work yet for you?

**Comment by parazyd** [comment]
@javiplx Let me know when you accept the invite and are able to push code to https://github.com/maemo-leste-extras/pyfuelpad

**Comment by javiplx** [comment]
Yep. I planned to ask about liblocation in main leste bugtracker. For now I've added an empty location.py to avoid crash.

**Comment by javiplx** [comment]
Code pushed. Is there anything else I should care?

**Comment by parazyd** [comment]
Great :)

I've written some maintenance instructions here, so please give them a look: https://leste.maemo.org/Development/Building_Packages#Maintenance_workflow

**Comment by javiplx** [comment]
I believe I added the required stuff. I'm used to prefix tags with `v`. Is that a problem? Should I use the same prefix for *upstream-tag* value?

**Comment by parazyd** [comment]
You can prepend it, yes. In this case it would be:

```upstream-tag=v%(version)s```

In the meantime, I'm setting up your builds on Jenkins.
It'll take some minutes, since I'm just doing this for the first time because you're the first contributor :)

I will email you with credentials and instructions.

**Comment by parazyd** [comment]
@javiplx I emailed your gmail address that I found in the git autorship. I couldn't send an email to the other one - the mailer said that it doesn't exist.

**Comment by javiplx** [comment]
I've added the missing `v`. When trying to launch a build on jenkins it says pending and also that my user has no permission. I tend to believe the second, and it's not currenly building anything. Should I just wait for some scheduled build or whatever? Is anything else we must do?

**Comment by parazyd** [comment]
Hi, you should have correct permissions now.

I did run a test job just now and it seems that there is an error in your dependencies, so you might want to fix that first: https://phoenix.maemo.org/job/pyfuelpad-binaries/architecture=amd64,label=amd64/1/console

Other than that, just try building again and I think it will be fine.

**Comment by parazyd** [comment]
Perhaps you want to incorporate the pull request you made into maemo/ascii :)

**Comment by MerlijnWajer** [comment]
So, `python-all-dev` could work as a replacement dependency I think.

**Comment by javiplx** [comment]
It was still using the old maemo files. I've just merged the branch which updates the packaging and now everything is green on jenkins builds.  
Failure is now on pyfuelpad-repos, and seems related to reprepro, although I don't understand the actual error and not sure whether is related to packaging or not.

**Comment by parazyd** [comment]
@javiplx I believe you need to add a `Section` header to the Source part in https://github.com/maemo-leste-extras/pyfuelpad/blob/maemo/ascii/debian/control

**Comment by javiplx** [comment]
You were right. Seems that section on the actual installable package was not enough.  
All three jobs are now on green
