### ISSUE TITLE
[REQ] gpxsee

### ISSUE THREAD

**Issue by halftux** [maemo-leste-extras/bugtracker#21]
Name: gpxsee
URL: https://github.com/tumic0/GPXSee
Comments: GPXSee is a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.

**Comment by parazyd** [comment]
Added to https://github.com/maemo-leste-extras/gpxsee and Jenkins.

Sorry for the delay.

**Comment by MerlijnWajer** [comment]
@halftux - care to import to extras if you have some time? The repo is empty at the moment

**Comment by halftux** [comment]
I am sorry I missed the invite please resend an invite, so that I can get access to the repo.

**Comment by MerlijnWajer** [comment]
@halftux - resent

**Comment by MerlijnWajer** [comment]
@halftux - did this ever make it to the repo?

**Comment by MerlijnWajer** [comment]
I've pushed a tag and run the job, let's see if it passes.
