### ISSUE TITLE
[REQ] wifi-switcher

### ISSUE THREAD

**Issue by bencoh** [maemo-leste-extras/bugtracker#22]
Name: wifi-switcher
URL: http://cgit.notk.org/bencoh/maemo-leste/wifi-switcher.git/
Comments: Wifi switcher applet for status-menu, ported from Maemo-extras:
http://maemo.org/packages/view/wifi-switcher/

**Comment by parazyd** [comment]
Created the repository here: https://github.com/maemo-leste-extras/wifi-switcher/
Also added to Jenkins.
Enjoy :)

(Please close the ticket if everything's ok)
