### ISSUE TITLE
[REQ] mstardict

### ISSUE THREAD

**Issue by norayr** [maemo-leste-extras/bugtracker#32]
Name: mstardict
URL: https://github.com/norayr/mstardict

this is a port from old fremantle sources. see changes: https://github.com/norayr/mstardict/commit/ca99d9d803dbf39ca2aee8f0d305a0e33ddc97b2

i generated the deb successfully, i need a repo to push and permission to build in phoenix.

**Comment by MerlijnWajer** [comment]
Done

**Comment by MerlijnWajer** [comment]
I can't seem to download dictionaries though, in the application
