### ISSUE TITLE
[REQ] Vulture Browser

### ISSUE THREAD

**Issue by le0nklcpp** [maemo-leste-extras/bugtracker#36]
Name: Vulture Browser
URL: https://gitlab.com/le0nklcpp/vulture-browser
Comments: Falkon Browser(QWebEngine) port for N900. IT WORKS. A bit better handling than Midori has.

**Comment by MerlijnWajer** [comment]
@le0nklcpp - I made a repo here https://github.com/maemo-leste-extras/vulture-browser and added you as a maintainer - you'll have to accept the request. Let me know if you can push code there, then we can look at the jenkins build.

Have you see the "qtwebbrowser" that we have in the repo? I don't know how it compares, but it's also qtwebengine.

**Comment by le0nklcpp** [comment]
Thanks, code is there now, I'll add build files soon

**Comment by le0nklcpp** [comment]
@MerlijnWajer pushed everything
The project uses CMake, do I need to do anything else?
I tried qtwebbrowser too, it has mobile-oriented interface with minimum required options while Falkon is a desktop browser.
There is also a problem with qtwebbrowser that makes it unusable - finger scrolling does not work, and there is no scrollbar, at least on N900
I think I can do something about it too

**Comment by MerlijnWajer** [comment]
I will try to look today and see if I can get the rest set up, thanks!

**Comment by MerlijnWajer** [comment]
As for qtwebbrowser, @IMbackK maintains it at the moment, and it indeed doesn't work well on the N900. I asked @sanderfoobar to look at making a hildon (maemo) UI for it, but maybe it makes sense to see what the best way forward is, so that we can collaborate on a central maemo browser.

**Comment by le0nklcpp** [comment]
Qt apps and QtWebBrowser in particular work better than I expected on Leste. I realized that it's even possible to scroll using hardware keyboard.
I don't have much time yet I would like to help with other projects

**Comment by MerlijnWajer** [comment]
(FYI I will get to it real soon, today or tomorrow at least, I've been very busy, apologies!)

**Comment by MerlijnWajer** [comment]
I have added it as a job to our jenkins now. Do you have an account on our jenkins/phoenix instance? Then I can give you access to the repo and you can then build it yourself whenever.

**Comment by le0nklcpp** [comment]
Thank you, I don't have one

**Comment by MerlijnWajer** [comment]
Would you mind creating one at https://phoenix.maemo.org/ ?

**Comment by le0nklcpp** [comment]
No problem, my email is in debian/control

**Comment by MerlijnWajer** [comment]
Okay, I'll make you an account. By the way, you might want to set Architecture to 'any' instead of just armhf, unless you think it won't work on aarch64 or amd64?

**Comment by MerlijnWajer** [comment]
I also tried to kick off a build now, and it failed:

```
dpkg-buildpackage: error: syntax error in debian/control at line 14: first block lacks a Source field
```

full log: https://phoenix.maemo.org/job/vulture-browser-source/1/consoleText

**Comment by le0nklcpp** [comment]
Thanks, fixed

**Comment by MerlijnWajer** [comment]
I ran another build: https://phoenix.maemo.org/job/vulture-browser-source/2/consoleText

I think you need to separate out the Source package and the binary packages, they can have the same name, though. You can look at some other extras repos on how to do it. Like here: https://github.com/maemo-leste-extras/maep/blob/maemo/chimaera/debian/control
