### ISSUE TITLE
[REQ] songrec

### ISSUE THREAD

**Issue by norayr** [maemo-leste-extras/bugtracker#38]
Name: songrec
URL: [songrec github page](https://github.com/marin-m/SongRec)
Comments: this is an open source shazam client for linux written in rust and gtk+.

**Comment by MerlijnWajer** [comment]
Sorry for the delay, I have made the repos now and will add Jenkins tomorrow!

https://github.com/maemo-leste-extras/songrec

**Comment by MerlijnWajer** [comment]
Done!
