### ISSUE TITLE
[REQ] hextool

### ISSUE THREAD

**Issue by halftux** [maemo-leste-extras/bugtracker#39]
Name: hextool
URL: http://maemo.org/packages/view/hextool/
Comments: Hex, Binary, Octal and Decimal Calculator

**Comment by MerlijnWajer** [comment]
Sorry for not getting back to you earlier, I was on a work trip. I'll make the repo now and set up Jenkins tomorrow.

**Comment by MerlijnWajer** [comment]
https://github.com/maemo-leste-extras/hextool

**Comment by halftux** [comment]
No problem and thank you. I will probably upload the code next week. Closing this when everything went fine.

**Comment by MerlijnWajer** [comment]
Done!
