### ISSUE TITLE
[REQ] comics daily

### ISSUE THREAD

**Issue by norayr** [maemo-leste-extras/bugtracker#40]
Name: comics daily
URL: https://github.com/norayr/comics_daily
Comments: I just wrote it and i enjoy it.
i wrote it because there is a similar app for sailfishos but it is unusable outside of sailfishos, so i wrote this for maemo and other linux systems.

**Comment by MerlijnWajer** [comment]
https://github.com/maemo-leste-extras/comics_daily :)
