### ISSUE TITLE
[REQ] otpn900

### ISSUE THREAD

**Issue by sicelo** [maemo-leste-extras/bugtracker#5]
Name: otpn900
URL: https://github.com/jwhitbeck/otpn900, forked in https://github.com/maemo-leste-extras/maeotp
Comments: Renamed to maeotp since (1) Leste supports more than just N900 now, and (2) the names of the binaries were conflicting with other packages available in Debian - see commit 6587cc346d989311a1f99043bd9b4a6e97f4485e

**Comment by parazyd** [comment]
Added to Jenkins. Closing.
