### ISSUE TITLE
[REQ] quicknote

### ISSUE THREAD

**Issue by sicelo** [maemo-leste-extras/bugtracker#6]
Name: quicknote
URL: https://github.com/epage/Quicknote (already forked at https://github.com/maemo-leste-extras/quicknote )
Comments:

**Comment by parazyd** [comment]
Added to Jenkins. Let me know if everything is in order, and if so, close the ticket :)

Thank you!

**Comment by parazyd** [comment]
@sicelo Is all ok? Can we close this?

**Comment by sicelo** [comment]
Not yet. Sorry. I will get it done this week though.

**Comment by sicelo** [comment]
Built successfully. Thanks!
