### ISSUE TITLE
[REQ] photolightmeter

### ISSUE THREAD

**Issue by norayr** [maemo-leste-extras/bugtracker#7]
Name: photolightmeter
URL: https://github.com/norayr/photolightmeter
Comments: it is a tool that helps photographers to set exposure by calculating aperture/shutter settings. it uses device's ambient light meter for that.

**Comment by parazyd** [comment]
Added it here and invited you: https://github.com/maemo-leste-extras/photolightmeter

**Comment by parazyd** [comment]
Closing this, since added.
