### ISSUE TITLE
[REQ] Personal IP Address

### ISSUE THREAD

**Issue by sicelo** [maemo-leste-extras/bugtracker#8]
Name: personal ip address
URL: http://maemo.org/downloads/product/Maemo5/personal-ip-address/
Comments: A desktop widget to display the IP address and interface you are connected to

**Comment by parazyd** [comment]
Created at https://github.com/maemo-leste-extras/personal-ip-address and added to jenkins. Let me know when I can close this ticket :)

**Comment by sicelo** [comment]
Will do. It is not working well yet, although it renders. I will upload it before the end of the week and others can help us fix it properly

**Comment by sicelo** [comment]
Builds successfully. Thank you
