### ISSUE TITLE
[REQ] mihphoto

### ISSUE THREAD

**Issue by halftux** [maemo-leste-extras/bugtracker#9]
Name: mihphoto
URL: https://github.com/halftux/MihPhoto/tree/leste
Comments: MihPhoto is meant to be a simple touchscreen-friendly image viewer based on Qt

To disable multitouch(default in desktop file) run in terminal: mihphoto --no-multitouch

**Comment by MerlijnWajer** [comment]
I've invited you to be a maintainer at https://github.com/maemo-leste-extras/mihphoto

**Comment by halftux** [comment]
Thank you
